#!/usr/bin/env php
<?php

// Apply custom PHP INI upload limits automatically (64M upload/post max size)
putenv('PHP_INI_SCAN_DIR=:' . __DIR__ . '/php-config');
$_ENV['PHP_INI_SCAN_DIR'] = ':' . __DIR__ . '/php-config';
$_SERVER['PHP_INI_SCAN_DIR'] = ':' . __DIR__ . '/php-config';

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
